language: go

go:
  - "1.11.x"

services:
  - mongodb

env:
  - TOGGLY_STORE_MONGO_URL=mongodb://127.0.0.1:27017/toggly

install:
  - docker --version
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - sleep 15

script:
  - go test ./... -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - docker build .
