version: '3'
services:
  toggly-server:
    build: .
    image: toggly/toggly-server
    depends_on: 
      - "db"
      - "redis"
    environment:
      TOGGLY_STORE_MONGO_URL: mongodb://db:27017/toggly
      TOGGLY_CACHE_TYPE: redis
      TOGGLY_CACHE_REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    networks:
      - toggly

  db:
    image: mongo
    volumes:
      - db-data:/data
    networks:
      - toggly

  redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - toggly

networks:
  toggly:

volumes:
  db-data:
  redis-data:
